# Generated by Django 5.1 on 2024-09-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='content',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
