# Generated by Django 5.1 on 2024-09-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_alter_challenge_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='challenge',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='challenge',
        ),
        migrations.AddField(
            model_name='challenge',
            name='goals',
            field=models.ManyToManyField(default=None, related_name='challenges', to='challenges.goal'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='skills',
            field=models.ManyToManyField(default=None, related_name='challenges', to='challenges.skill'),
        ),
    ]
