# Generated by Django 5.1 on 2024-09-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_remove_goal_challenge_remove_skill_challenge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='goals',
            field=models.ManyToManyField(blank=True, default=None, related_name='challenges', to='challenges.goal'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='skills',
            field=models.ManyToManyField(blank=True, default=None, related_name='challenges', to='challenges.skill'),
        ),
    ]
