# Generated by Django 5.1 on 2024-09-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_alter_challenge_goals_alter_challenge_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
