# Generated by Django 5.1 on 2024-09-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_alter_challenge_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='month',
        ),
        migrations.AddField(
            model_name='challenge',
            name='month',
            field=models.ManyToManyField(related_name='challenges', to='challenges.month'),
        ),
    ]
