# Generated by Django 5.1 on 2024-09-19 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_remove_challenge_month_challenge_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='content',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='label',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
