# Generated by Django 5.1.1 on 2024-09-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_alter_challenge_content_alter_challenge_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
